apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.helloWorld.name}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.services.helloWorld.name}}
  ports:
    - port: {{ .Values.services.helloWorld.port}}
      targetPort: {{ .Values.services.helloWorld.targetPort}}
      nodePort: {{ .Values.services.helloWorld.nodePort}}